evaluation:
  force_extract_answer: true 
  timeout_duration: 10
  result_dir: ../results/evaluate-results
  dataset: FinMMR
  ans_extract_model_name: ans_extract_model
  model_name: <model_name>
  subset: <subset>
  prompt_type: <prompt_type>

llms:
  ans_extract_model:
    model_id: <model_id>
    api_key: <api_key>
    base_url: <base_url>
    support_system_role: true
    reasoner: false
    rpm: 500
    sampling_args:
      temperature: 0.0
      max_tokens: 8192
      top_p: 1.0
